scalaVersion := "2.11.6"
libraryDependencies += "com.github.nscala-time" %% "nscala-time" % "2.0.0"
libraryDependencies += "org.twitter4j" % "twitter4j-stream" % "4.0.3"
libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.6.4"
libraryDependencies += "com.gu" %% "content-api-client" % "5.3"
libraryDependencies += "com.typesafe.slick" %% "slick" % "3.0.0"